const positiveWords = [
  "peace",
  "collaboration",
  "unity",
  "together",
  "joint",
  "partnership",
  "alliance",
  "harmony",
  "agreement",
  "accord",
  "reconciliation",
  "compromise",
  "mutual",
  "love",
  "cooperation",
  "shared",
  "collective",
  "community",
  "brotherhood",
  "sisterhood",
  "solidarity",
  "friendship",
  "love",
  "respect",
  "tolerance",
  "empathy",
  "compassion",
  "kindness",
  "generosity",
  "altruism",
  "charity",
  "philanthropy",
  "support",
  "help",
  "assist",
  "aid",
  "contribute",
  "give",
  "donate",
  "volunteer",
  "unite",
  "connect",
  "bond",
  "link",
  "bridge",
  "overcome",
  "resolve",
  "settle",
  "address",
  "manage",
  "deal",
  "negotiate",
  "mediate",
  "facilitate",
  "promote",
  "advance",
  "foster",
  "encourage",
  "empower",
  "celebrate",
  "honor",
  "appreciate",
  "recognize",
  "acknowledge",
  "validate",
  "uplift",
  "inspire",
  "motivate",
  "energize",
  "renew",
  "revitalize",
  "refresh",
  "regenerate",
  "stimulate",
  "invigorate",
  "cultivate",
  "nurture",
  "develop",
  "grow",
  "evolve",
  "transform",
  "change",
  "progress",
  "improve",
  "enhance",
  "upgrade",
  "modernize",
  "innovate",
  "create",
  "invent",
  "discover",
  "explore",
  "expand",
  "enrich",
  "augment",
  "enlarge",
  "extend",
  "widen",
  "deepen",
  "broaden",
  "heighten",
  "intensify",
  "strengthen",
  "fortify",
  "secure",
  "protect",
  "defend",
  "safeguard",
  "preserve",
  "maintain",
  "sustain",
  "uphold",
  "reinforce",
  "bolster",
  "propel",
  "accelerate",
  "streamline",
  "optimize",
  "maximize",
  "utilize",
  "leverage",
  "harness",
  "exploit",
  "capitalize",
  "benefit",
  "serve",
  "fulfill",
  "satisfy",
  "meet",
  "exceed",
  "surpass",
  "attain",
  "realize",
  "accomplish",
  "implement",
  "deliver",
  "provide",
  "offer",
  "present",
  "furnish",
  "supply",
  "procure",
  "gain",
];

const cultureWords = [
  "israel",
  "israeli",
  "arab",
  "arabic",
  "palestine",
  "palestinian",
  "jew",
  "jewish",
  "judaism",
  "muslim",
  "islam",
  "christian",
  "religion",
  "gaza",
  "westbank",
  "west bank",
];
const test = {
  title: "gaza",
  description: "love",
};

const scraperFilter = (scrapedArticle) => {
  for (const positiveWord of positiveWords) {
    if (
      scrapedArticle.title.toLowerCase().includes(positiveWord) ||
      scrapedArticle.description.toLowerCase().includes(positiveWord)
    ) {
      for (const cultureWord of cultureWords) {
        if (
          scrapedArticle.title.toLowerCase().includes(cultureWord) ||
          scrapedArticle.description.toLowerCase().includes(cultureWord)
        )
          return true;
      }
    }
  }
  return false;
};

export default scraperFilter;
